export const DEFAULT_SERVICES = [
  { id: "s1", name: "Wash & Fold", category: "laundry", price: 200, pricing_mode: "per_weight", unit_label: "kg", description: "Machine wash, dry and fold per kilogram" },
  { id: "s2", name: "Wash & Iron", category: "laundry", price: 300, pricing_mode: "per_weight", unit_label: "kg", description: "Machine wash, dry and press per kilogram" },
  { id: "s3", name: "Pressing Only", category: "laundry", price: 150, pricing_mode: "per_unit", unit_label: "item", description: "Iron and press per garment" },
  { id: "s4", name: "Dry Clean — Shirt", category: "laundry", price: 350, pricing_mode: "per_unit", unit_label: "item", description: "Professional dry cleaning per shirt" },
  { id: "s5", name: "Dry Clean — Suit", category: "laundry", price: 800, pricing_mode: "per_unit", unit_label: "item", description: "Full suit dry cleaning" },
  { id: "s6", name: "Dry Clean — Dress", category: "laundry", price: 600, pricing_mode: "per_unit", unit_label: "item", description: "Dry cleaning for dresses and gowns" },
  { id: "s7", name: "Dry Clean — Jacket", category: "laundry", price: 500, pricing_mode: "per_unit", unit_label: "item", description: "Jacket and blazer dry cleaning" },
  { id: "s8", name: "Blanket Wash", category: "laundry", price: 400, pricing_mode: "per_unit", unit_label: "item", description: "Machine wash and dry for blankets" },
  { id: "s9", name: "Duvet Cleaning", category: "laundry", price: 600, pricing_mode: "per_unit", unit_label: "item", description: "Full duvet wash and fluff" },
  { id: "s10", name: "Curtain Cleaning", category: "laundry", price: 500, pricing_mode: "per_weight", unit_label: "kg", description: "Curtain wash and press per kilogram" },
  { id: "s11", name: "Rug Cleaning", category: "laundry", price: 800, pricing_mode: "per_unit", unit_label: "item", description: "Small to medium rug wash" },
  { id: "s12", name: "Delicates Hand Wash", category: "laundry", price: 350, pricing_mode: "per_unit", unit_label: "item", description: "Hand wash for silk, lace, and delicate fabrics" },
  { id: "s13", name: "Stain Removal", category: "laundry", price: 200, pricing_mode: "per_unit", unit_label: "item", description: "Pre-treatment and stain removal per garment" },
  { id: "s14", name: "Shoe Cleaning", category: "laundry", price: 250, pricing_mode: "per_unit", unit_label: "pair", description: "Shoe wash and polish per pair" },
  { id: "s15", name: "Wedding Dress Cleaning", category: "laundry", price: 3500, pricing_mode: "flat", unit_label: "", description: "Full wedding dress preservation cleaning" },
  { id: "s16", name: "Leather Care", category: "laundry", price: 1200, pricing_mode: "per_unit", unit_label: "item", description: "Leather jacket cleaning and conditioning" },
  { id: "s17", name: "Express Service", category: "laundry", price: 500, pricing_mode: "flat", unit_label: "", description: "Express surcharge — same day collection" },
  { id: "s18", name: "Haircut", category: "cosmetics-beauty", price: 500, pricing_mode: "flat", unit_label: "", description: "Standard haircut — wash included" },
  { id: "s19", name: "Manicure", category: "cosmetics-beauty", price: 800, pricing_mode: "flat", unit_label: "", description: "Full manicure with polish" },
  { id: "s20", name: "Facial Treatment", category: "cosmetics-beauty", price: 1200, pricing_mode: "flat", unit_label: "", description: "Deep cleanse, exfoliation, mask and moisturise" },
  { id: "s21", name: "Makeup Application", category: "cosmetics-beauty", price: 1500, pricing_mode: "flat", unit_label: "", description: "Full face makeup application" },
  { id: "s22", name: "Eyelash Extensions", category: "cosmetics-beauty", price: 2000, pricing_mode: "flat", unit_label: "", description: "Full set classic eyelash extensions" },
  { id: "s23", name: "Waxing — Full Leg", category: "cosmetics-beauty", price: 1500, pricing_mode: "flat", unit_label: "", description: "Full leg wax treatment" },
  { id: "s24", name: "Threading", category: "cosmetics-beauty", price: 300, pricing_mode: "flat", unit_label: "", description: "Eyebrow threading and shaping" },
  { id: "s25", name: "Pedicure", category: "nails-salon", price: 1000, pricing_mode: "flat", unit_label: "", description: "Full pedicure with polish" },
  { id: "s26", name: "Gel Nails", category: "nails-salon", price: 1500, pricing_mode: "flat", unit_label: "", description: "Full set gel nail application" },
  { id: "s27", name: "Acrylic Nails", category: "nails-salon", price: 2000, pricing_mode: "flat", unit_label: "", description: "Full set acrylic nails" },
  { id: "s28", name: "Nail Art", category: "nails-salon", price: 500, pricing_mode: "flat", unit_label: "", description: "Custom nail art design per hand" },
  { id: "s29", name: "Nail Repair", category: "nails-salon", price: 300, pricing_mode: "per_unit", unit_label: "nail", description: "Single broken nail repair" },
  { id: "s30", name: "Paraffin Wax Treatment", category: "nails-salon", price: 800, pricing_mode: "flat", unit_label: "", description: "Paraffin wax dip for hands" },
  { id: "s31", name: "Oil Change", category: "automotive-car", price: 2500, pricing_mode: "flat", unit_label: "", description: "Engine oil change — labour included" },
  { id: "s32", name: "Car Wash", category: "automotive-car", price: 600, pricing_mode: "flat", unit_label: "", description: "Exterior + interior vacuum" },
  { id: "s33", name: "Interior Detailing", category: "automotive-car", price: 2500, pricing_mode: "flat", unit_label: "", description: "Deep interior clean, seats, carpets, dashboard" },
  { id: "s34", name: "Wax Polish", category: "automotive-car", price: 1500, pricing_mode: "flat", unit_label: "", description: "Hand wax and polish — exterior only" },
  { id: "s35", name: "Upholstery Cleaning", category: "automotive-car", price: 3000, pricing_mode: "flat", unit_label: "", description: "Shampoo and extract fabric upholstery" },
  { id: "s36", name: "Haircut", category: "barber-grooming", price: 400, pricing_mode: "flat", unit_label: "", description: "Standard haircut" },
  { id: "s37", name: "Shave", category: "barber-grooming", price: 300, pricing_mode: "flat", unit_label: "", description: "Straight razor shave" },
  { id: "s38", name: "Beard Trim", category: "barber-grooming", price: 250, pricing_mode: "flat", unit_label: "", description: "Beard shaping and trimming" },
  { id: "s39", name: "Hair Styling", category: "barber-grooming", price: 500, pricing_mode: "per_hour", unit_label: "hr", description: "Custom styling per hour" },
  { id: "s40", name: "Kids Haircut", category: "barber-grooming", price: 300, pricing_mode: "flat", unit_label: "", description: "Haircut for children under 12" },
  { id: "s41", name: "Hot Towel Shave", category: "barber-grooming", price: 600, pricing_mode: "flat", unit_label: "", description: "Premium hot towel straight razor shave" },
  { id: "s42", name: "Hair Wash & Blow Dry", category: "barber-grooming", price: 350, pricing_mode: "flat", unit_label: "", description: "Shampoo, condition and blow dry" },
  { id: "s43", name: "Grooming Package", category: "barber-grooming", price: 1200, pricing_mode: "flat", unit_label: "", description: "Haircut + shave + beard trim" },
  { id: "s44", name: "Oil Change", category: "auto-repair-garage", price: 2500, pricing_mode: "flat", unit_label: "", description: "Engine oil change with filter" },
  { id: "s45", name: "Tire Rotation", category: "auto-repair-garage", price: 500, pricing_mode: "per_unit", unit_label: "tire", description: "Tire rotation and balancing per tyre" },
  { id: "s46", name: "Brake Pad Replacement", category: "auto-repair-garage", price: 3500, pricing_mode: "flat", unit_label: "", description: "Front or rear brake pad replacement" },
  { id: "s47", name: "Engine Diagnostic", category: "auto-repair-garage", price: 1500, pricing_mode: "flat", unit_label: "", description: "Full engine diagnostic scan" },
  { id: "s48", name: "Battery Replacement", category: "auto-repair-garage", price: 500, pricing_mode: "flat", unit_label: "", description: "Battery replacement — labour only" },
  { id: "s49", name: "AC Gas Refill", category: "auto-repair-garage", price: 2500, pricing_mode: "flat", unit_label: "", description: "Air conditioning gas refill and check" },
  { id: "s50", name: "Full Service", category: "auto-repair-garage", price: 8000, pricing_mode: "flat", unit_label: "", description: "Major service — oil, filters, plugs, fluids" },
  { id: "s51", name: "Wheel Alignment", category: "auto-repair-garage", price: 2000, pricing_mode: "flat", unit_label: "", description: "Front and rear wheel alignment" },
  { id: "s52", name: "Portrait Session", category: "photography", price: 3500, pricing_mode: "per_hour", unit_label: "hr", description: "Professional portrait photography per hour" },
  { id: "s53", name: "Event Coverage", category: "photography", price: 15000, pricing_mode: "flat", unit_label: "", description: "Full event photography — up to 4 hours" },
  { id: "s54", name: "Product Photography", category: "photography", price: 2000, pricing_mode: "per_hour", unit_label: "hr", description: "Studio product photography per hour" },
  { id: "s55", name: "Wedding Package", category: "photography", price: 45000, pricing_mode: "flat", unit_label: "", description: "Full wedding day coverage + edited gallery" },
  { id: "s56", name: "Photo Editing", category: "photography", price: 500, pricing_mode: "per_unit", unit_label: "photo", description: "Professional photo retouching per image" },
  { id: "s57", name: "Video Shoot", category: "photography", price: 5000, pricing_mode: "per_hour", unit_label: "hr", description: "Videography per hour" },
  { id: "s58", name: "Standard Clean", category: "cleaning-services", price: 3000, pricing_mode: "flat", unit_label: "", description: "Standard home clean — 2 bedroom" },
  { id: "s59", name: "Deep Clean", category: "cleaning-services", price: 6000, pricing_mode: "flat", unit_label: "", description: "Deep clean — 2 bedroom, all surfaces" },
  { id: "s60", name: "Office Cleaning", category: "cleaning-services", price: 5000, pricing_mode: "flat", unit_label: "", description: "Office cleaning — up to 10 desks" },
  { id: "s61", name: "Window Cleaning", category: "cleaning-services", price: 1500, pricing_mode: "flat", unit_label: "", description: "Interior window cleaning — up to 10 windows" },
  { id: "s62", name: "Carpet Cleaning", category: "cleaning-services", price: 800, pricing_mode: "per_unit", unit_label: "room", description: "Shampoo and extract carpet per room" },
  { id: "s63", name: "Move-in/Move-out Clean", category: "cleaning-services", price: 8000, pricing_mode: "flat", unit_label: "", description: "Full clean for moving tenants" },
  { id: "s64", name: "Post-Construction Clean", category: "cleaning-services", price: 10000, pricing_mode: "flat", unit_label: "", description: "Heavy duty clean after renovation" },
  { id: "s65", name: "Screen Replacement", category: "electronics-repair", price: 3000, pricing_mode: "flat", unit_label: "", description: "Phone screen replacement — parts + labour" },
  { id: "s66", name: "Battery Replacement", category: "electronics-repair", price: 1500, pricing_mode: "flat", unit_label: "", description: "Phone battery replacement" },
  { id: "s67", name: "Charging Port Repair", category: "electronics-repair", price: 2000, pricing_mode: "flat", unit_label: "", description: "Charging port repair/replacement" },
  { id: "s68", name: "Software Troubleshooting", category: "electronics-repair", price: 1000, pricing_mode: "per_hour", unit_label: "hr", description: "Software diagnostics and repair per hour" },
  { id: "s69", name: "Water Damage Repair", category: "electronics-repair", price: 5000, pricing_mode: "flat", unit_label: "", description: "Water damage assessment and repair" },
  { id: "s70", name: "Data Recovery", category: "electronics-repair", price: 3500, pricing_mode: "flat", unit_label: "", description: "File and data recovery service" },
  { id: "s71", name: "Phone Unlocking", category: "electronics-repair", price: 1000, pricing_mode: "flat", unit_label: "", description: "Network unlock service" },
  { id: "s72", name: "Laptop Repair", category: "electronics-repair", price: 2500, pricing_mode: "flat", unit_label: "", description: "Basic laptop diagnostics and repair" },
];

export const pricingModeLabels = {
  flat: "Flat rate",
  per_unit: "Per item",
  per_weight: "Per kg",
  per_hour: "Per hour",
};
