import { useState, useEffect, useRef, useCallback } from "react";
import PageLayout from "../components/layout/PageLayout";
import { getShopId } from "../lib/shop";
import { supabase } from "../lib/supabase";
import { formatPrice } from "../lib/format";
import { useSettings } from "../hooks/useSettings";
import QRCode from "qrcode";
import {
  FiLink, FiCopy, FiShare2, FiSmartphone, FiFileText, FiGrid, FiStar, FiDownload, FiCheck, FiExternalLink,
} from "react-icons/fi";

function showToast(msg, type) {
  const el = document.createElement("div");
  el.className = `fixed top-4 right-4 z-50 px-4 py-3 rounded-xl text-sm font-semibold shadow-xl transition-all duration-300 ${
    type === "error" ? "bg-red-500 text-white" : "bg-blue-600 text-white"
  }`;
  el.textContent = msg;
  document.body.appendChild(el);
  setTimeout(() => el.remove(), 2500);
}

export default function Marketing() {
  const { whatsapp, websiteUrl } = useSettings();
  const [catalogue, setCatalogue] = useState([]);
  const [selectedId, setSelectedId] = useState("");
  const [generatedLink, setGeneratedLink] = useState("");
  const [copied, setCopied] = useState(false);
  const [qrType, setQrType] = useState("website");
  const [qrUrl, setQrUrl] = useState("");
  const qrCanvasRef = useRef(null);
  const [loading, setLoading] = useState(true);

  const selectedProduct = catalogue.find((c) => c.id === selectedId);

  useEffect(() => {
    (async () => {
      const shopId = await getShopId();
      const { data } = await supabase
        .from("products")
        .select("*")
        .eq("shop_id", shopId)
        .order("name")
        .limit(200);
      if (data) setCatalogue(data);
      setLoading(false);
    })();
  }, []);

  const generateLink = useCallback(() => {
    if (!selectedProduct) return;
    const base = websiteUrl || window.location.origin;
    setGeneratedLink(`${base}/p/${selectedProduct.id}`);
    setCopied(false);
  }, [selectedProduct, websiteUrl]);

  async function copyLink() {
    try {
      await navigator.clipboard.writeText(generatedLink);
      setCopied(true);
      showToast("Link copied!", "success");
    } catch {
      showToast("Failed to copy", "error");
    }
  }

  function shareWhatsApp() {
    if (!selectedProduct || !whatsapp) return;
    const text = encodeURIComponent(`Hi! I'd like to order ${selectedProduct.name} — ${generatedLink}`);
    window.open(`https://wa.me/${whatsapp.replace(/[^0-9]/g, "")}?text=${text}`, "_blank");
  }

  function testWhatsApp() {
    if (!whatsapp) { showToast("Set your WhatsApp number in Settings first", "error"); return; }
    const text = encodeURIComponent("Hi! I'd like to know more about your products.");
    window.open(`https://wa.me/${whatsapp.replace(/[^0-9]/g, "")}?text=${text}`, "_blank");
  }

  function printCatalog() {
    const printWin = window.open("", "_blank");
    if (!printWin) { showToast("Please allow popups for this feature", "error"); return; }
    printWin.document.write(`
      <html><head><title>Catalog</title>
      <style>
        body { font-family: system-ui, sans-serif; padding: 40px; color: #1e293b; }
        h1 { font-size: 24px; margin-bottom: 8px; }
        .sub { color: #64748b; font-size: 14px; margin-bottom: 32px; }
        table { width: 100%; border-collapse: collapse; font-size: 14px; }
        th { text-align: left; padding: 10px 12px; border-bottom: 2px solid #e2e8f0; color: #64748b; font-size: 12px; text-transform: uppercase; }
        td { padding: 10px 12px; border-bottom: 1px solid #e2e8f0; }
        .price { font-weight: 600; }
        @media print { body { padding: 20px; } }
      </style></head><body>
      <h1>Product Catalog</h1>
      <p class="sub">${catalogue.length} product(s)</p>
      <table><thead><tr><th>Product</th><th>Category</th><th>Type</th><th>Price</th></tr></thead><tbody>
      ${catalogue.map((c) => `<tr><td>${c.name}</td><td>${c.category}</td><td>${c.type}</td><td class="price">${formatPrice(c.price)}</td></tr>`).join("")}
      </tbody></table>
      <p style="margin-top: 32px; font-size: 11px; color: #94a3b8;">Generated by Keel — ${new Date().toLocaleDateString()}</p>
      </body></html>
    `);
    printWin.document.close();
    printWin.onload = () => { printWin.print(); };
  }

  useEffect(() => {
    (async () => {
      const text = qrType === "website" ? (websiteUrl || window.location.origin) : `https://wa.me/${whatsapp?.replace(/[^0-9]/g, "") || ""}`;
      setQrUrl(text);
      if (qrCanvasRef.current && text) {
        try {
          await QRCode.toCanvas(qrCanvasRef.current, text, { width: 180, margin: 2, color: { dark: "#1e293b", light: "#ffffff" } });
        } catch { /* ignore */ }
      }
    })();
  }, [qrType, websiteUrl, whatsapp]);

  function downloadQR() {
    if (!qrCanvasRef.current) return;
    const link = document.createElement("a");
    link.download = `keel-qr-${qrType}.png`;
    link.href = qrCanvasRef.current.toDataURL("image/png");
    link.click();
  }

  async function toggleNewArrival(item, value) {
    const shopId = await getShopId();
    await supabase.from("products").update({ new_arrival: value }).eq("id", item.id).eq("shop_id", shopId);
    setCatalogue((prev) => prev.map((c) => (c.id === item.id ? { ...c, new_arrival: value } : c)));
    showToast(value ? "Marked as new arrival" : "Removed new arrival tag", "success");
  }

  const whatsappNumber = whatsapp || "";

  if (loading) {
    return (
      <PageLayout title="Marketing">
        <div className="space-y-3">{[...Array(5)].map((_, i) => <div key={i} className="h-14 bg-white/5 rounded-xl animate-pulse" />)}</div>
      </PageLayout>
    );
  }

  return (
    <PageLayout title="Marketing">
      <div className="max-w-2xl mx-auto space-y-6">

        {/* 1. Shareable Product Links */}
        <div className="bg-white dark:bg-[#16213e] rounded-xl border border-gray-100 dark:border-white/10 p-5">
          <div className="flex items-center gap-2 mb-4">
            <FiLink size={14} className="text-gray-400" />
            <h3 className="text-sm font-medium text-gray-800 dark:text-white">Shareable Product Links</h3>
          </div>
          <div className="flex flex-col sm:flex-row gap-2 mb-3">
            <select
              value={selectedId}
              onChange={(e) => { setSelectedId(e.target.value); setGeneratedLink(""); }}
              className="flex-1 border border-gray-200 dark:border-white/10 rounded-lg px-3 py-2 text-sm bg-white dark:bg-[#1a1a2e] text-gray-800 dark:text-white focus:outline-none focus:border-blue-400"
            >
              <option value="">Select a product...</option>
              {catalogue.map((c) => (<option key={c.id} value={c.id}>{c.name} — {formatPrice(c.price)}</option>))}
            </select>
            <button
              onClick={generateLink}
              disabled={!selectedId}
              className="w-full sm:w-auto bg-blue-600 text-white text-xs px-4 py-2 rounded-lg hover:bg-blue-700 transition-all disabled:opacity-50"
            >
              Generate
            </button>
          </div>
          {generatedLink && (
            <div className="bg-gray-50 dark:bg-[#1a1a2e] rounded-lg p-3 border border-gray-200 dark:border-white/10">
              <p className="text-xs text-gray-500 dark:text-slate-400 mb-1">Shareable URL</p>
              <p className="text-sm font-mono text-gray-800 dark:text-white break-all mb-3">{generatedLink}</p>
              <div className="flex gap-2">
                <button onClick={copyLink} className="flex items-center gap-1.5 text-xs bg-white dark:bg-[#16213e] border border-gray-200 dark:border-white/10 px-3 py-1.5 rounded-lg text-gray-600 dark:text-slate-400 hover:text-blue-600 dark:hover:text-blue-400 transition-all">
                  {copied ? <FiCheck size={14} /> : <FiCopy size={14} />} {copied ? "Copied" : "Copy Link"}
                </button>
                <button onClick={shareWhatsApp} disabled={!whatsapp} className="flex items-center gap-1.5 text-xs bg-white dark:bg-[#16213e] border border-gray-200 dark:border-white/10 px-3 py-1.5 rounded-lg text-gray-600 dark:text-slate-400 hover:text-green-600 dark:hover:text-green-400 transition-all disabled:opacity-50">
                  <FiShare2 size={14} /> Share on WhatsApp
                </button>
              </div>
            </div>
          )}
        </div>

        {/* 2. WhatsApp Order Button */}
        <div className="bg-white dark:bg-[#16213e] rounded-xl border border-gray-100 dark:border-white/10 p-5">
          <div className="flex items-center gap-2 mb-4">
            <FiSmartphone size={14} className="text-gray-400" />
            <h3 className="text-sm font-medium text-gray-800 dark:text-white">WhatsApp "Order Now" Button</h3>
          </div>
          <p className="text-xs text-gray-400 dark:text-slate-500 mb-2">
            WhatsApp number: <span className="font-mono text-gray-700 dark:text-slate-300">{whatsappNumber || "Not set"}</span>
            <a href="/settings" className="text-blue-600 dark:text-blue-400 ml-2 hover:underline">Edit</a>
          </p>
          <div className="bg-gray-50 dark:bg-[#1a1a2e] rounded-lg p-4 border border-gray-200 dark:border-white/10 mb-3">
            <p className="text-xs text-gray-400 dark:text-slate-500 mb-2">Preview</p>
            <a
              href={`https://wa.me/${whatsappNumber.replace(/[^0-9]/g, "")}`}
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-2 bg-green-500 text-white text-sm px-5 py-2.5 rounded-xl hover:bg-green-600 transition-all font-medium"
            >
              <FiSmartphone size={16} /> Order Now via WhatsApp
            </a>
          </div>
          <button onClick={testWhatsApp} className="flex items-center gap-1.5 text-xs text-blue-600 dark:text-blue-400 hover:underline">
            <FiExternalLink size={14} /> Test link
          </button>
        </div>

        {/* 3. Catalog PDF Export */}
        <div className="bg-white dark:bg-[#16213e] rounded-xl border border-gray-100 dark:border-white/10 p-5">
          <div className="flex items-center gap-2 mb-4">
            <FiFileText size={14} className="text-gray-400" />
            <h3 className="text-sm font-medium text-gray-800 dark:text-white">Catalog PDF Export</h3>
          </div>
          <p className="text-xs text-gray-400 dark:text-slate-500 mb-3">
            {catalogue.length} product(s) in your catalog. Generate a print-friendly version.
          </p>
          <button
            onClick={printCatalog}
            disabled={catalogue.length === 0}
            className="flex items-center gap-2 bg-blue-600 text-white text-sm px-4 py-2 rounded-lg hover:bg-blue-700 transition-all disabled:opacity-50"
          >
            <FiFileText size={16} /> Generate & Print Catalog
          </button>
        </div>

        {/* 4. Business QR Code */}
        <div className="bg-white dark:bg-[#16213e] rounded-xl border border-gray-100 dark:border-white/10 p-5">
          <div className="flex items-center gap-2 mb-4">
            <FiGrid size={14} className="text-gray-400" />
            <h3 className="text-sm font-medium text-gray-800 dark:text-white">Business QR Code</h3>
          </div>
          <div className="flex gap-2 mb-4">
            <button
              onClick={() => setQrType("website")}
              className={`flex-1 py-2 rounded-lg text-xs font-semibold border transition-all ${
                qrType === "website" ? "bg-blue-600 text-white border-blue-500" : "bg-white dark:bg-[#1a1a2e] text-gray-500 dark:text-slate-400 border-gray-200 dark:border-white/10"
              }`}
            >
              Website URL
            </button>
            <button
              onClick={() => setQrType("whatsapp")}
              className={`flex-1 py-2 rounded-lg text-xs font-semibold border transition-all ${
                qrType === "whatsapp" ? "bg-blue-600 text-white border-blue-500" : "bg-white dark:bg-[#1a1a2e] text-gray-500 dark:text-slate-400 border-gray-200 dark:border-white/10"
              }`}
            >
              WhatsApp
            </button>
          </div>
          <p className="text-xs text-gray-400 dark:text-slate-500 mb-3 truncate">Scan to open: {qrUrl || "—"}</p>
          <div className="flex items-center gap-4">
            <div className="bg-white rounded-xl p-2 border border-gray-200">
              <canvas ref={qrCanvasRef} width={180} height={180} className="block" />
            </div>
            <button onClick={downloadQR} className="flex items-center gap-1.5 text-xs bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 transition-all">
              <FiDownload size={14} /> Download PNG
            </button>
          </div>
        </div>

        {/* 5. New Arrivals */}
        <div className="bg-white dark:bg-[#16213e] rounded-xl border border-gray-100 dark:border-white/10 p-5">
          <div className="flex items-center gap-2 mb-4">
            <FiStar size={14} className="text-gray-400" />
            <h3 className="text-sm font-medium text-gray-800 dark:text-white">New Arrival Announcements</h3>
          </div>
          {catalogue.length === 0 ? (
            <p className="text-xs text-gray-400 dark:text-slate-500 text-center py-6">No products yet. Add products from the Inventory page.</p>
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead>
                  <tr className="border-b border-gray-200 dark:border-white/10 bg-gray-50 dark:bg-[#1a1a2e]">
                    <th className="px-3 py-2 text-xs font-semibold text-left text-gray-500 dark:text-slate-400 uppercase">Product</th>
                    <th className="px-3 py-2 text-xs font-semibold text-left text-gray-500 dark:text-slate-400 uppercase">Category</th>
                    <th className="px-3 py-2 text-xs font-semibold text-right text-gray-500 dark:text-slate-400 uppercase">Price</th>
                    <th className="px-3 py-2 text-xs font-semibold text-center text-gray-500 dark:text-slate-400 uppercase">New Arrival</th>
                  </tr>
                </thead>
                <tbody>
                  {catalogue.map((item, i) => (
                    <tr key={item.id} className={`border-b border-white/5 hover:bg-black/[0.03] dark:hover:bg-white/[0.05] transition-colors ${i === catalogue.length - 1 ? "border-0" : ""}`}>
                      <td className="px-3 py-2.5 font-medium text-gray-800 dark:text-white">{item.name}</td>
                      <td className="px-3 py-2.5 text-gray-500 dark:text-slate-400 text-xs capitalize">{item.category}</td>
                      <td className="px-3 py-2.5 text-right text-gray-800 dark:text-white">{formatPrice(item.price)}</td>
                      <td className="px-3 py-2.5 text-center">
                        <button
                          onClick={() => toggleNewArrival(item, !item.new_arrival)}
                          className={`w-10 h-5 rounded-full transition-all relative ${
                            item.new_arrival ? "bg-blue-600" : "bg-gray-300 dark:bg-gray-600"
                          }`}
                          aria-label={`Toggle new arrival for ${item.name}`}
                        >
                          <span className={`absolute top-0.5 w-4 h-4 bg-white rounded-full shadow transition-transform ${
                            item.new_arrival ? "translate-x-[2px]" : "translate-x-[-14px]"
                          }`} />
                        </button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </div>

      </div>
    </PageLayout>
  );
}
